apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {VM_BASENAME}-{BATCH_ID}-{vm-id}
  namespace: {vm-ns}
  labels:
    batch-id: "{BATCH_ID}"
    vm-basename: "{VM_BASENAME}"
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: {VM_BASENAME}-{BATCH_ID}-{vm-id}
    spec:
      sourceRef:
        kind: DataSource
        name: {DATASOURCE}
        namespace: {DATASOURCE_NS}
      storage:
        accessModes:
        - {ACCESS_MODE}
        resources:
          requests:
            storage: {STORAGE_SIZE}
        volumeMode: Block
        storageClassName: {STORAGE_CLASS}
  runStrategy: {RUN_STRATEGY}
  template:
    metadata:
      labels:
        kubevirt.io/domain: {VM_BASENAME}
        batch-id: "{BATCH_ID}"
        vm-basename: "{VM_BASENAME}"
    spec:
      domain:
        cpu:
          cores: {VM_CPU_CORES}
        memory:
          guest: {VM_MEMORY}
        devices:
          disks:
          - disk:
              bus: virtio
            name: vda
          {CLOUDINIT_DISK}
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        {DOMAIN_FIRMWARE}
        {RESOURCES}
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: {VM_BASENAME}-{BATCH_ID}-{vm-id}
        name: vda
      {CLOUDINIT_VOLUME}
